image: maven:3.3-jdk-11

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

Discovery-Server-Test:
  stage: test
  script:
    - cd discovery-server
    - pwd
    - mvn clean
    - mvn compile
    - mvn test

Movie-Catalog-Test:
  stage: test
  script:
    - cd movie-catalog-service
    - pwd
    - mvn clean
    - mvn compile
    - mvn test

Movie-Info-Test:
  stage: test
  script:
    - cd movie-info-service
    - pwd
    - mvn clean
    - mvn compile
    - mvn test

Ratings-Data-Test:
  stage: test
  script:
    - cd ratings-data-service
    - pwd
    - mvn clean
    - mvn compile
    - mvn test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
